### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tommyeddysony** [RJPenic/CVRPTW#3]
after running the code it only prints me the number of vehicles and the time taken, it does not give me the path of the nodes it runs. Do you have a solution?

**Comment by RJPenic** [comment]
Paths of vehicles are not printed in the teminal but stored in the files that are generated after certain amount of time. For example, after 1 minute of runtime program will generate a file called res-1-instance.txt which will contain best found paths for each vehicle in the format described on that last page of [problem description document](../blob/main/problem_description.pdf).
