### ISSUE TITLE
main.py  list out of range 

### ISSUE THREAD

**Issue by boboxxx** [RJPenic/CVRPTW#4]
Traceback (most recent call last):
  File "/Users/chenweibo/Desktop/CVRPTW-main/cvrptw/main.py", line 7, in <module>
    instanceName = str(sys.argv[1])
IndexError: list index out of range

**Comment by RJPenic** [comment]
Are you sure you provided the program with the name of the instance file? Your run command should look something like this: `python3 cvrptw/main.py i1.txt`

**Comment by boboxxx** [comment]
I run this project like this python3 cvrptw/main.py i1.txt. But it's does't have any reaction . Actually i  don't konw how to run this project.

**Comment by boboxxx** [comment]
I think if run in your way , I need to run every file i1.txt, i2.txt ......  Can you use a loop to read file to improve efficiency?

**Comment by RJPenic** [comment]
Program is structured in such way that you can give it only one instance file at the time. You can easily create a script that calls the program multiple times (each time with the different instance file) though.
